#  --- RENDERING ---

# if false, an 800 x 600 window will be used
fullscreen_enabled: false

vsync_enabled: true

screen_depth: 1000.0
screen_near: 0.1

shadowmap_size: 1080

#  --- SNOW CRYSTAL GENERATOR ---

hexagon_lattice_width: 100
hexagon_lattice_height: 100

# increase this to slow the automton down if it is growing too quickly
automaton_step_every_nth_frame: 1

alpha: 1.0 # weighting factor
beta: 0.4 # background level
gamma: 0.000005 # growth constant